name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" 

      - name: Copy .env.example to .env
        run: cp ./INKOSTEL/.env.example ./INKOSTEL/.env

      - name: Run Composer
        run: composer install --no-interaction
        working-directory: ./INKOSTEL

      - name: Run Tests
        run: vendor/bin/phpunit --testsuite Unit
        working-directory: ./INKOSTEL
